pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/SaiNirmalReddy/lcrs-application19.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t lcrs-app .'
            }
        }

    }
}
