pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t lcrs-app -f docker/Dockerfile .'
            }
        }

        stage('Push Docker Image')
            steps {
                sh 'docker push sai1docker/lcrs-app'
    }
}
